// Every card in the app. src = where it comes from; the quiz cards are word
// for word off the five graded quizzes, with what was written on the paper
// (mine) and how it went (ok: true / false / "part" / null for blank).

const V = (src, n, g, a, mine, ok, note) =>
  ({ src, sec: "Vocab", n, p: "Meaning?", g, a, mine, ok, note });

const QUIZ = [
  // ── Quiz 1 · ch. 1 vocab ─────────────────────────────────────────
  V("Q1", 1, "ἄρα", "so, then, consequently", "until", false),
  V("Q1", 2, "οὐαί", "woe!", "", null),
  V("Q1", 3, "πειράζω", "I test, tempt", "test", "part"),
  V("Q1", 4, "ναός, ὁ", "temple", "temple", true),
  V("Q1", 5, "τεσσεράκοντα", "forty", "fourty", true),
  V("Q1", 6, "σταυρόω", "I crucify", "crucify", true),
  V("Q1", 7, "ἱκανός", "sufficient, able, worthy", "able", true),
  V("Q1", 8, "κρατέω", "I grasp, hold (fast), arrest", "", null),
  V("Q1", 9, "θλῖψις, -εως, ἡ", "tribulation, affliction, oppression", "", null),
  V("Q1", 10, "ἰσχυρός", "strong, mighty, powerful", "stronger", "part", "ἰσχυρότερος is “stronger”; ἰσχυρός is just “strong”."),
  V("Q1", 11, "οὐκέτι", "no longer", "no longer", true),
  V("Q1", 12, "θρίξ, τριχός, ἡ", "hair", "", null),
  V("Q1", 13, "ποταμός, ὁ", "river", "river", true),
  V("Q1", 14, "ἔτος, -ους, τό", "year", "year", true),
  V("Q1", 15, "ὀπίσω", "after, behind", "", null),
  V("Q1", 16, "ἄφεσις, -εως, ἡ", "forgiveness", "ready", false),
  V("Q1", 17, "διέρχομαι", "I go through", "through", "part"),
  V("Q1", 18, "ἀπαγγέλλω", "I report, announce, proclaim", "preach, proclaim", true),
  V("Q1", 19, "προσφέρω", "I bring to, offer", "give", false),
  V("Q1", 20, "χώρα, ἡ", "region, district, country", "until", false),
  V("Q1", 21, "ἐπιγινώσκω", "I know, recognize", "I know", true),
  V("Q1", 22, "καθίζω", "I cause to sit down, appoint; I sit", "", null),
  V("Q1", 23, "ἀποδίδωμι", "I give back, pay", "pay", true),
  V("Q1", 24, "ἑτοιμάζω", "I make ready, prepare", "", null),
  V("Q1", 25, "εὐδοκέω", "I am well pleased", "well pleased", true),
  V("Q1", 26, "φυλακή, ἡ", "prison, guard, watch", "prison", true),
  V("Q1", 27, "βάπτισμα, -ατος, τό", "baptism", "baptize", "part", "Noun, not verb: “baptism”."),
  V("Q1", 28, "ἔρημος, ἡ", "desert, wilderness", "desert", true),
  V("Q1", 29, "ἐκπορεύομαι", "I go out", "go out", true),
  V("Q1", 30, "Σατανᾶς, -ᾶ, ὁ", "Satan", "satan", true),
  V("Q1", 31, "θηρίον, τό", "animal, wild beast", "", null),
  V("Q1", 32, "ἄχρι", "until", "woe", false, "You swapped ἄχρι and οὐαί. ἄχρι = until, οὐαί = woe."),
  V("Q1", 33, "μετάνοια, ἡ", "repentance", "repent", "part", "Noun: “repentance”."),
  V("Q1", 34, "διακονέω", "I serve, minister", "I serve", true),
  V("Q1", 35, "Ἰορδάνης, -ου, ὁ", "Jordan", "Jordan", true),
  V("Q1", 36, "πρό", "before (+ gen)", "before", true),
  V("Q1", 37, "Ἠσαΐας, ὁ", "Isaiah", "Isaiah", true),
  V("Q1", 38, "ὅμοιος", "like, similar", "", null),
  V("Q1", 39, "ἐνδύω", "I clothe myself, put on, wear", "separate", false),
  V("Q1", 40, "δεύτερος", "second", "second", true),

  // ── Quiz 2 · ch. 2 nominative, vocative, accusative ───────────────
  V("Q2", 1, "ἁμαρτάνω", "I sin", "sin", true),
  V("Q2", 2, "ἄξιος", "worthy", "", null),
  V("Q2", 3, "ἐργάζομαι", "I work", "", null),
  V("Q2", 4, "εὐλογέω", "I bless", "reckon", false, "“Reckon” is λογίζομαι. εὐ-λογέω = speak well of → bless."),
  V("Q2", 5, "θαυμάζω", "I marvel, wonder, am amazed", "", null),
  V("Q2", 6, "θύρα, ἡ", "door", "", null),
  V("Q2", 7, "καινός", "new", "", null),
  V("Q2", 8, "μικρός", "small, little", "small", true),
  V("Q2", 9, "παρίστημι", "I present; I stand by, am present", "confidence", false, "“Confidence” is παρρησία. παρ-ίστημι = stand beside."),
  V("Q2", 10, "πρόβατον, τό", "sheep", "", null),
  V("Q2", 11, "ἐγγίζω", "I draw near, approach", "", null),
  V("Q2", 12, "σπέρμα, -ατος, τό", "seed, offspring", "seed", true),
  { src: "Q2", sec: "Translation", n: 1, p: "Translate.", g: "καὶ ὁ λόγος ἦν πρὸς τὸν θεόν", a: "And the Word was with God.", mine: "And the word was with God", ok: true },
  { src: "Q2", sec: "Categories", n: 2, p: "What are the three main uses of the nominative case?", a: "Subject · Predicate nominative · Apposition", mine: "Subject, Predicate Nominative, Apposition", ok: true },
  { src: "Q2", sec: "Categories", n: 3, p: "What are the five substantival uses of the accusative case?", a: "Direct object · Double accusative · Cognate · Subject of the infinitive · Apposition", mine: "Direct Object, Appelation, Double, Cognate, Subject of the Infinitive", ok: "part", note: "Appellation is a nominative use. The fifth accusative is Apposition." },
  { src: "Q2", sec: "Identification", n: 4, p: "Classify the underlined word — case and specific category.", g: "Παῦλος <u>δοῦλος</u> Χριστοῦ Ἰησοῦ", a: "Nominative of apposition (Rom 1:1) — “Paul, a servant of Christ Jesus”: δοῦλος renames Παῦλος.", mine: "Absolute Accusative", ok: false, note: "δοῦλος is nominative, not accusative. (Παῦλος itself, as a letter opening, is the nominative absolute.)" },
  { src: "Q2", sec: "Identification", n: 5, p: "Classify the underlined words — case and specific category.", g: "οὕτως γὰρ ἠγάπησεν ὁ θεὸς <u>τὸν κόσμον</u>", a: "Accusative, direct object — “God so loved the world.”", mine: "Apposition Nominative", ok: false },
  { src: "Q2", sec: "Identification", n: 6, p: "Classify and explain the underlined words.", g: "Ἐν ἀρχῇ ἦν ὁ λόγος, καὶ ὁ λόγος ἦν πρὸς τὸν θεόν, καὶ <u>θεὸς</u> ἦν ὁ <u>λόγος</u>", a: "λόγος = subject (it has the article). θεός = predicate nominative: no article, placed before the verb. Colwell’s rule: a definite predicate nominative before the verb usually drops the article.", mine: "Predicate Nominative", ok: "part", note: "Name both words and give the reason (article → subject; Colwell)." },
  { src: "Q2", sec: "Extra credit", n: 7, p: "περισσεύω means…", g: "περισσεύω", a: "I abound, overflow, have more than enough", mine: "I test", ok: false, note: "“I test” is πειράζω." },
  { src: "Q2", sec: "Extra credit", n: 8, p: "Classify the underlined word.", g: "δικαιούμενοι <u>δωρεὰν</u> τῇ αὐτοῦ χάριτι", a: "Adverbial accusative of manner — “justified freely by his grace” (Rom 3:24).", mine: "", ok: null },
  { src: "Q2", sec: "Extra credit", n: 9, p: "What is the pecking order for telling a predicate nominative from a subject?", a: "PAP: Pronoun → Article → Proper name. Whichever has the higher one is the subject.", mine: "P, A, P", ok: true, note: "Be ready to spell it out." },

  // ── Quiz 3 · genitives ────────────────────────────────────────────
  V("Q3", 1, "ἀγρός, ὁ", "field", "field", true),
  V("Q3", 2, "διαθήκη, ἡ", "covenant", "covenant", true),
  V("Q3", 3, "διακονία, ἡ", "service, ministry", "deacon", false, "Deacon is διάκονος. διακονία is the service itself."),
  V("Q3", 4, "δικαιόω", "I justify, declare righteous", "justify", true),
  V("Q3", 5, "ἱερεύς, -έως, ὁ", "priest", "priest", true),
  V("Q3", 6, "λογίζομαι", "I reckon, count, consider", "reckon", true),
  V("Q3", 7, "ὑποστρέφω", "I turn back, return", "to turn back", true),
  V("Q3", 8, "ποῦ", "where?", "where?", true),
  V("Q3", 9, "φανερόω", "I reveal, make known", "reveal", true),
  V("Q3", 10, "χωρίς", "without, apart from (+ gen)", "without", true),
  V("Q3", 11, "ἀκάθαρτος", "unclean, impure", "unclean, impure", true),
  V("Q3", 12, "διότι", "for, because, therefore", "for, because", true),
  V("Q3", 13, "ἔξεστιν", "it is lawful, permitted", "it is lawful", true),
  V("Q3", 14, "ὀργή, ἡ", "anger, wrath, punishment", "anger, wrath", true),
  V("Q3", 15, "παραγίνομαι", "I come, arrive, appear", "I come, arrive", true),
  { src: "Q3", sec: "Translation", n: 2, p: "Translate.", g: "Νυνὶ δὲ χωρὶς νόμου δικαιοσύνη θεοῦ πεφανέρωται", a: "But now, apart from the law, the righteousness of God has been revealed (made manifest).", mine: "But now without … God’s righteousness is revealed", ok: "part", note: "νόμου = “(the) law”; πεφανέρωται is perfect: “has been revealed”." },
  { src: "Q3", sec: "Categories", n: "3.1", p: "What are the three main / overarching categories of the genitive?", a: "Adjectival · Verbal · Adverbial (plus “other uses”).", mine: "Listed sub-uses, no category names", ok: false },
  { src: "Q3", sec: "Categories", n: "3.2", p: "What are the two categories of verbal genitives?", a: "Subjective · Objective", mine: "Subjective and Objective", ok: true },
  { src: "Q3", sec: "Classify", n: "3.3a", p: "Classify the underlined genitive.", g: "Ἰάκωβον τὸν τοῦ <u>Ζεβεδαίου</u>", a: "Relationship — “James the son of Zebedee.”", mine: "relationship", ok: true },
  { src: "Q3", sec: "Classify", n: "3.3b", p: "Classify the underlined genitive.", g: "Νυνὶ δὲ χωρὶς <u>νόμου</u> δικαιοσύνη θεοῦ πεφανέρωται", a: "Separation (“apart from”) — object of the improper preposition χωρίς.", mine: "Means", ok: false, note: "Check this one with your notes — it is a genitive after χωρίς, not a genitive of means." },
  { src: "Q3", sec: "Classify", n: "3.3c", p: "Classify the underlined genitive.", g: "ἓν <u>τῶν πλοίων</u>", a: "Partitive — “one of the boats” (the whole the one is taken from).", mine: "Descriptive", ok: false },
  { src: "Q3", sec: "Classify", n: "3.3d", p: "Classify the underlined genitive.", g: "ἔχετε πίστιν <u>θεοῦ</u>", a: "Objective — “have faith in God”: God receives the faith.", mine: "Objective", ok: true },
  { src: "Q3", sec: "Classify", n: "3.3e", p: "Classify the underlined genitive.", g: "μείζων ἐστὶν ὁ θεὸς τῆς <u>καρδίας</u> ἡμῶν", a: "Comparison — after the comparative μείζων: “greater than our heart.”", mine: "Attributive", ok: false },
  { src: "Q3", sec: "Extra credit", n: 1, p: "What is the difference between means and agency?", a: "Means = impersonal (a thing). Agency = personal (someone).", mine: "Agency is a person, means is not", ok: true },
  { src: "Q3", sec: "Extra credit", n: 2, p: "δυνατός means…", g: "δυνατός", a: "powerful, able, possible", mine: "powerful", ok: true },
  { src: "Q3", sec: "Extra credit", n: 3, p: "Classify the underlined genitive.", g: "καὶ εἰσελθόντες εἰς τὸν οἶκον <u>Φιλίππου</u>", a: "Possession — “the house of Philip.”", mine: "Possession", ok: true },
  { src: "Q3", sec: "Extra credit", n: 4, p: "What is the difference between an objective and a subjective genitive?", a: "Subjective: the genitive noun DOES the action in the head noun (“love of Christ” = Christ loves). Objective: the genitive noun RECEIVES it (“faith in God” = God is trusted).", mine: "Objective is done towards the object and subjective is towards the subject", ok: "part" },

  // ── Quiz 4 · datives ──────────────────────────────────────────────
  V("Q4", 1, "φόβος, ὁ", "fear", "fear", true),
  V("Q4", 2, "σωτηρία, ἡ", "salvation", "savior", false, "Savior is σωτήρ. -ία = the thing: salvation."),
  V("Q4", 3, "μισέω", "I hate", "hate", true),
  V("Q4", 4, "Ἰούδας, ὁ", "Judas, Judah, Jude", "Jude, Judas", true),
  V("Q4", 5, "ἴδε", "look! behold!", "look, behold", true),
  V("Q4", 6, "Ἰάκωβος, ὁ", "James, Jacob", "James", true),
  V("Q4", 7, "θυσία, ἡ", "sacrifice", "sacrifice", true),
  V("Q4", 8, "ἐπικαλέω", "I call upon", "I call upon", true),
  V("Q4", 9, "ἐπιθυμία, ἡ", "lust, craving, desire", "lust, craving, desire", true),
  V("Q4", 10, "ἐλεέω", "I show mercy", "I show mercy", true),
  { src: "Q4", sec: "Categories", n: "2.1", p: "What are the three main categories of datives?", a: "Pure dative · Locative · Instrumental (plus “other uses”).", mine: "PORT / Locative / HIT / MAMA", ok: "part", note: "Write the names, not just the acrostics." },
  { src: "Q4", sec: "Categories", n: "2.2", p: "What are the three types of locative datives?", a: "Place · Sphere · Time", mine: "Sphere, Influence, Time", ok: "part", note: "Place, not “influence”." },
  { src: "Q4", sec: "Categories", n: "2.3", p: "What are the two types of dative of personal interest?", a: "Advantage · Disadvantage", mine: "Agg", ok: false },
  { src: "Q4", sec: "Categories", n: "2.4", p: "Name two types of “Other Uses” of the dative.", a: "Any two of: Cause · Cognate · Apposition · Direct object", mine: "BEAD", ok: false },
  { src: "Q4", sec: "Classify", n: "3a", p: "Classify the underlined dative.", g: "δὸς δόξαν τῷ <u>θεῷ</u>", a: "Indirect object — “give glory to God.”", mine: "Means", ok: false },
  { src: "Q4", sec: "Classify", n: "3b", p: "Classify the underlined dative.", g: "<u>ὑμῖν</u> γάρ ἐστιν ἡ ἐπαγγελία", a: "Possession — “the promise is for you / yours” (dative + εἰμί).", mine: "Reference", ok: false },
  { src: "Q4", sec: "Classify", n: "3c", p: "Classify the underlined dative.", g: "ἀναστενάξας τῷ <u>πνεύματι</u> αὐτοῦ", a: "Sphere — “sighing deeply in his spirit.”", mine: "Sphere", ok: true },
  { src: "Q4", sec: "Classify", n: "3d", p: "Classify the underlined dative.", g: "κατακόπτων ἑαυτὸν <u>λίθοις</u>", a: "Means — “cutting himself with stones.”", mine: "Possession", ok: false },
  { src: "Q4", sec: "Classify", n: "3e", p: "Classify the underlined dative.", g: "συνταφέντες <u>αὐτῷ</u> ἐν τῷ βαπτισμῷ", a: "Association — “buried with him” (note the συν- prefix).", mine: "Means", ok: false },
  { src: "Q4", sec: "Translation", n: 4, p: "Translate and classify the underlined dative.", g: "οὗτος ἦν ἐν <u>ἀρχῇ</u> πρὸς τὸν θεόν.", a: "“He was in the beginning with God.” ἀρχῇ = dative of time.", mine: "Time (he was with God in the beginning)", ok: true },
  { src: "Q4", sec: "Extra credit", n: 1, p: "What prefix is often used when there is a dative of association?", a: "συν- (σύν, “with”)", mine: "Mitos", ok: false },
  { src: "Q4", sec: "Extra credit", n: 2, p: "παράκλησις, -εως, ἡ means…", g: "παράκλησις", a: "encouragement, comfort, exhortation", mine: "comfort", ok: true },
  { src: "Q4", sec: "Extra credit", n: 3, p: "Classify the underlined dative.", g: "ἡ δὲ Ἡρῳδιὰς ἐνεῖχεν <u>αὐτῷ</u>", a: "Disadvantage (personal interest) — “held a grudge against him.”", mine: "Agency", ok: false },

  // ── Quiz 5 · article and adjective ────────────────────────────────
  V("Q5", 1, "ἀναβλέπω", "I look up; I regain sight", "I look up, see", true),
  V("Q5", 2, "γνωρίζω", "I make known, reveal", "I make known, reveal", true),
  V("Q5", 3, "δουλεύω", "I serve (as a slave), am a slave", "I am a slave", true),
  V("Q5", 4, "μυστήριον, τό", "mystery", "mystery", true),
  V("Q5", 5, "νικάω", "I conquer, overcome", "I conquer, overcome", true),
  V("Q5", 6, "οἶνος, ὁ", "wine", "wine", true),
  V("Q5", 7, "σταυρός, ὁ", "cross", "cross", true),
  V("Q5", 8, "συνίημι", "I understand", "understand", true),
  V("Q5", 9, "φωνέω", "I call", "I call", true),
  V("Q5", 10, "χήρα, ἡ", "widow", "widow", true),
  V("Q5", 11, "προφητεύω", "I prophesy", "I prophesy", true),
  V("Q5", 12, "πόθεν", "from where?", "from where?", true),
  V("Q5", 13, "καθαρός", "pure, clean", "pure/clean", true),
  V("Q5", 14, "ἥκω", "I have come", "I have come", true),
  V("Q5", 15, "ἄρτι", "now", "now", true),
  { src: "Q5", sec: "Translation", n: 2, p: "Translate.", g: "καὶ τὸ φῶς ἐν τῇ σκοτίᾳ φαίνει", a: "And the light shines in the darkness.", mine: "And the light shines in the darkness", ok: true },
  { src: "Q5", sec: "Categories", n: "3.1", p: "What are the five types of particularizing articles?", a: "Simple identification · Par excellence · Monadic · With abstract nouns · Previous reference (anaphoric)", mine: "Monadic, Abstract, Par excellence, Simple identification, Anaphoric", ok: true },
  { src: "Q5", sec: "Categories", n: "3.2", p: "True or false: if a noun has no article, it is always indefinite.", a: "False — it can be indefinite, qualitative, or definite.", mine: "False", ok: true },
  { src: "Q5", sec: "Categories", n: "3.3", p: "True or false: an article can function as a pronoun.", a: "True — personal, relative, possessive, demonstrative, alternative.", mine: "True", ok: true },
  { src: "Q5", sec: "Categories", n: "3.4", p: "List three types of adjectives.", a: "Any three of: Predicate · Attributive · Substantival · Adverbial", mine: "Predicate, Attributive, Substantival", ok: true },
  { src: "Q5", sec: "Classify", n: "4a", p: "Classify the underlined article or adjective.", g: "<u>οἱ</u> δὲ εἶπαν αὐτῷ", a: "Article as a personal pronoun — “they said to him.”", mine: "Demonstrative pronoun", ok: false },
  { src: "Q5", sec: "Classify", n: "4b", p: "Classify the underlined article or adjective.", g: "<u>ἡ</u> σωτηρία ἐκ τῶν Ἰουδαίων ἐστίν", a: "Article with an abstract noun — “salvation is from the Jews.”", mine: "Par excellence", ok: false },
  { src: "Q5", sec: "Classify", n: "4c", p: "Classify the underlined article or adjective.", g: "οὕτως γὰρ ἠγάπησεν ὁ θεὸς τὸν κόσμον, ὥστε <u>τὸν</u> υἱὸν τὸν μονογενῆ ἔδωκεν", a: "Monadic — there is only one such Son.", mine: "Monadic", ok: true },
  { src: "Q5", sec: "Classify", n: "4d", p: "Classify the underlined article or adjective.", g: "ὁ ἄνθρωπος <u>ἀγαθός</u>", a: "Predicate — “the man is good.” Article on the noun, none on the adjective.", mine: "Attributive", ok: false },
  { src: "Q5", sec: "Classify", n: "4e", p: "Classify the underlined article or adjective.", g: "ἄνθρωπος ὁ <u>ἀγαθός</u>", a: "Attributive — “the good man.” The adjective has the article.", mine: "Predicate", ok: false, note: "You had 4d and 4e backwards. Article in front of the adjective → attributive." },
  { src: "Q5", sec: "Classify", n: "4f", p: "Classify the underlined article or adjective.", g: "σὺ εἶ ὁ <u>ἅγιος</u>", a: "Substantival — “you are the Holy One”: the adjective stands as the noun.", mine: "Attributive", ok: false },
  { src: "Q5", sec: "Extra credit", n: 1, p: "Classify the adjective.", g: "ἄνθρωπος ἀγαθός", a: "Ambiguous: no article anywhere, so attributive (“a good man”) or predicate (“a man is good”) — context decides.", mine: "Attributive", ok: "part" },
  { src: "Q5", sec: "Extra credit", n: 2, p: "What does the elative adjective do?", a: "Intensifies — a comparative or superlative used to mean “very …”.", mine: "Amplifies, as though saying very", ok: true },
  { src: "Q5", sec: "Extra credit", n: 3, p: "Describe the Granville Sharp rule.", g: "τοῦ μεγάλου θεοῦ καὶ σωτῆρος ἡμῶν Ἰησοῦ Χριστοῦ", a: "One article governing two singular, personal, non-proper nouns of the same case joined by καί → they refer to the same person. “Our great God and Savior, Jesus Christ.”", mine: "One article over two names joined by καί, usually one person", ok: true, note: "Add: singular, personal, NOT proper names, same case." },
  { src: "Q5", sec: "Extra credit", n: 4, p: "What is the difference between the monadic article and par excellence?", a: "Monadic: only one exists (one of a kind). Par excellence: there are many, but this is THE one — the best example.", mine: "Monadic = one of a kind; par excellence = the one who deserves it more than anyone", ok: true },
];

// ── Study-guide items the quizzes don't cover ───────────────────────
const CH12 = [
  { src: "Ch12", sec: "Ch. 12", p: "What is a pronoun?", a: "A word that stands in for a noun (its antecedent), so the noun need not be repeated." },
  { src: "Ch12", sec: "Ch. 12", p: "What are the types of pronouns? Explain each.", a: "Personal — who is talking (ἐγώ, σύ, αὐτός)\nDemonstrative — points: this/that (οὗτος, ἐκεῖνος)\nRelative — links back: who/which (ὅς, ἥ, ὅ)\nInterrogative — asks: who? what? (τίς, τί)\nIndefinite — someone, anyone (τις, τι)\nReflexive — the self (ἐμαυτόν, ἑαυτόν)\nReciprocal — each other (ἀλλήλων)", note: "Me · This · Who · Who? · Anyone · Myself · Each other" },
  { src: "Ch12", sec: "Ch. 12", p: "What can an adverb modify?", a: "A verb, an adjective, or another adverb. (With an article it can even act as a noun or adjective.)" },
  { src: "Ch12", sec: "Ch. 12", p: "What is the difference between a proper and an improper preposition?", a: "Proper: can be prefixed to a verb to make a compound (ἐκ + πορεύομαι → ἐκπορεύομαι).\nImproper: never compounded with a verb; really an adverb used as a preposition, usually + genitive (χωρίς, ἐνώπιον, ὀπίσω, ἄχρι, ἕως, ἔμπροσθεν)." },
];

// Classifications drawn from the three midterm passages.
const PASSAGE = [
  ["Mark 1:1", "<u>Ἀρχὴ</u> τοῦ εὐαγγελίου Ἰησοῦ Χριστοῦ", "Nominative absolute — a title/heading, no verb."],
  ["Mark 1:1", "Ἰησοῦ Χριστοῦ <u>υἱοῦ</u> θεοῦ", "Genitive of apposition — renames Ἰησοῦ Χριστοῦ."],
  ["Mark 1:2", "ἐν τῷ Ἠσαΐᾳ τῷ <u>προφήτῃ</u>", "Dative of apposition — “Isaiah, the prophet.”"],
  ["Mark 1:3", "<u>φωνὴ</u> βοῶντος ἐν τῇ ἐρήμῳ", "Nominative absolute — stands alone, no verb."],
  ["Mark 1:4", "βάπτισμα <u>μετανοίας</u>", "Genitive of description — “a baptism of repentance.”"],
  ["Mark 1:4", "εἰς ἄφεσιν <u>ἁμαρτιῶν</u>", "Objective genitive — sins are what get forgiven."],
  ["Mark 1:5", "ἐν τῷ Ἰορδάνῃ <u>ποταμῷ</u>", "Dative of apposition — “the Jordan River.”"],
  ["Mark 1:6", "τρίχας <u>καμήλου</u>", "Genitive of material — hair made from a camel."],
  ["Mark 1:7", "ὁ <u>ἰσχυρότερός</u> μου", "Comparative adjective (substantival) — “the one mightier than I”; μου = genitive of comparison."],
  ["Mark 1:8", "ἐβάπτισα ὑμᾶς <u>ὕδατι</u>", "Dative of means — “with water.”"],
  ["Mark 1:9", "ἐν ἐκείναις ταῖς <u>ἡμέραις</u>", "Dative of time."],
  ["Mark 1:11", "σὺ εἶ ὁ <u>υἱός</u> μου", "Predicate nominative (σύ is the subject — pronoun outranks)."],
  ["Mark 1:11", "ὁ υἱός μου ὁ <u>ἀγαπητός</u>", "Attributive adjective (second attributive position)."],
  ["Mark 1:13", "<u>τεσσεράκοντα ἡμέρας</u>", "Accusative of measure (extent of time) — “for forty days.”"],
  ["Mark 1:13", "<u>οἱ ἄγγελοι</u> διηκόνουν αὐτῷ", "Nominative subject; αὐτῷ = dative direct object (διακονέω takes the dative)."],
  ["John 1:1", "<u>Ἐν ἀρχῇ</u> ἦν ὁ λόγος", "Dative of time."],
  ["John 1:6", "ὄνομα <u>αὐτῷ</u> Ἰωάννης", "Dative of possession — “his name.”"],
  ["Rom 3:19", "ὑπόδικος γένηται πᾶς ὁ κόσμος <u>τῷ θεῷ</u>", "Dative of personal interest / reference — accountable to God."],
  ["Rom 3:20", "ἐπίγνωσις <u>ἁμαρτίας</u>", "Objective genitive — sin is what is known."],
  ["Rom 3:23", "ὑστεροῦνται τῆς <u>δόξης</u> τοῦ θεοῦ", "Genitive direct object — verbs of lacking take the genitive."],
  ["Rom 3:24", "<u>δωρεὰν</u> τῇ αὐτοῦ χάριτι", "Adverbial accusative of manner — “freely.”"],
  ["Rom 3:24", "δωρεὰν τῇ αὐτοῦ <u>χάριτι</u>", "Dative of means — “by his grace.”"],
  ["Rom 3:26", "εἰς τὸ εἶναι <u>αὐτὸν</u> δίκαιον", "Accusative subject of the infinitive εἶναι — “that he might be just.”"],
].map(([ref, g, a]) => ({ src: "Passage", sec: ref, p: "Classify the underlined word.", g, a }));

const TRANSLATE = [
  ["John 1:1", "Ἐν ἀρχῇ ἦν ὁ λόγος, καὶ ὁ λόγος ἦν πρὸς τὸν θεόν, καὶ θεὸς ἦν ὁ λόγος.", "In the beginning was the Word, and the Word was with God, and the Word was God."],
  ["John 1:2", "οὗτος ἦν ἐν ἀρχῇ πρὸς τὸν θεόν.", "He was in the beginning with God."],
  ["John 1:3", "πάντα δι’ αὐτοῦ ἐγένετο, καὶ χωρὶς αὐτοῦ ἐγένετο οὐδὲ ἕν. ὃ γέγονεν", "All things came into being through him, and apart from him not one thing came into being. What has come into being"],
  ["John 1:4", "ἐν αὐτῷ ζωὴ ἦν, καὶ ἡ ζωὴ ἦν τὸ φῶς τῶν ἀνθρώπων·", "in him was life, and the life was the light of men."],
  ["John 1:5", "καὶ τὸ φῶς ἐν τῇ σκοτίᾳ φαίνει, καὶ ἡ σκοτία αὐτὸ οὐ κατέλαβεν.", "And the light shines in the darkness, and the darkness did not overcome it."],
  ["John 1:6", "Ἐγένετο ἄνθρωπος, ἀπεσταλμένος παρὰ θεοῦ, ὄνομα αὐτῷ Ἰωάννης·", "There came a man, sent from God; his name was John."],
  ["John 1:7", "οὗτος ἦλθεν εἰς μαρτυρίαν ἵνα μαρτυρήσῃ περὶ τοῦ φωτός, ἵνα πάντες πιστεύσωσιν δι’ αὐτοῦ.", "He came as a witness, to testify about the light, so that all might believe through him."],
  ["Mark 1:1", "Ἀρχὴ τοῦ εὐαγγελίου Ἰησοῦ Χριστοῦ υἱοῦ θεοῦ.", "The beginning of the gospel of Jesus Christ, the Son of God."],
  ["Mark 1:2", "Καθὼς γέγραπται ἐν τῷ Ἠσαΐᾳ τῷ προφήτῃ· ἰδοὺ ἀποστέλλω τὸν ἄγγελόν μου πρὸ προσώπου σου, ὃς κατασκευάσει τὴν ὁδόν σου·", "As it is written in Isaiah the prophet: “Behold, I send my messenger before your face, who will prepare your way,"],
  ["Mark 1:3", "φωνὴ βοῶντος ἐν τῇ ἐρήμῳ· ἑτοιμάσατε τὴν ὁδὸν κυρίου, εὐθείας ποιεῖτε τὰς τρίβους αὐτοῦ,", "a voice of one crying in the wilderness: ‘Prepare the way of the Lord, make his paths straight.’”"],
  ["Mark 1:4", "ἐγένετο Ἰωάννης ὁ βαπτίζων ἐν τῇ ἐρήμῳ καὶ κηρύσσων βάπτισμα μετανοίας εἰς ἄφεσιν ἁμαρτιῶν.", "John came, baptizing in the wilderness and proclaiming a baptism of repentance for the forgiveness of sins."],
  ["Mark 1:5", "καὶ ἐξεπορεύετο πρὸς αὐτὸν πᾶσα ἡ Ἰουδαία χώρα καὶ οἱ Ἱεροσολυμῖται πάντες, καὶ ἐβαπτίζοντο ὑπ’ αὐτοῦ ἐν τῷ Ἰορδάνῃ ποταμῷ ἐξομολογούμενοι τὰς ἁμαρτίας αὐτῶν.", "And the whole Judean region and all the people of Jerusalem were going out to him, and they were being baptized by him in the Jordan River, confessing their sins."],
  ["Mark 1:6", "καὶ ἦν ὁ Ἰωάννης ἐνδεδυμένος τρίχας καμήλου καὶ ζώνην δερματίνην περὶ τὴν ὀσφὺν αὐτοῦ καὶ ἐσθίων ἀκρίδας καὶ μέλι ἄγριον.", "And John was clothed in camel’s hair with a leather belt around his waist, and he ate locusts and wild honey."],
  ["Mark 1:7", "καὶ ἐκήρυσσεν λέγων· ἔρχεται ὁ ἰσχυρότερός μου ὀπίσω μου, οὗ οὐκ εἰμὶ ἱκανὸς κύψας λῦσαι τὸν ἱμάντα τῶν ὑποδημάτων αὐτοῦ.", "And he was preaching, saying, “After me comes one mightier than I, the strap of whose sandals I am not worthy to stoop down and untie."],
  ["Mark 1:8", "ἐγὼ ἐβάπτισα ὑμᾶς ὕδατι, αὐτὸς δὲ βαπτίσει ὑμᾶς πνεύματι ἁγίῳ.", "I baptized you with water, but he will baptize you with the Holy Spirit.”"],
  ["Mark 1:9", "Καὶ ἐγένετο ἐν ἐκείναις ταῖς ἡμέραις ἦλθεν Ἰησοῦς ἀπὸ Ναζαρὲτ τῆς Γαλιλαίας καὶ ἐβαπτίσθη εἰς τὸν Ἰορδάνην ὑπὸ Ἰωάννου.", "And in those days Jesus came from Nazareth of Galilee and was baptized in the Jordan by John."],
  ["Mark 1:10", "καὶ εὐθὺς ἀναβαίνων ἐκ τοῦ ὕδατος εἶδεν σχιζομένους τοὺς οὐρανοὺς καὶ τὸ πνεῦμα ὡς περιστερὰν καταβαῖνον εἰς αὐτόν·", "And immediately, coming up out of the water, he saw the heavens being torn open and the Spirit descending on him like a dove."],
  ["Mark 1:11", "καὶ φωνὴ ἐγένετο ἐκ τῶν οὐρανῶν· σὺ εἶ ὁ υἱός μου ὁ ἀγαπητός, ἐν σοὶ εὐδόκησα.", "And a voice came from the heavens: “You are my beloved Son; with you I am well pleased.”"],
  ["Mark 1:12", "Καὶ εὐθὺς τὸ πνεῦμα αὐτὸν ἐκβάλλει εἰς τὴν ἔρημον.", "And immediately the Spirit drives him out into the wilderness."],
  ["Mark 1:13", "καὶ ἦν ἐν τῇ ἐρήμῳ τεσσεράκοντα ἡμέρας πειραζόμενος ὑπὸ τοῦ σατανᾶ, καὶ ἦν μετὰ τῶν θηρίων, καὶ οἱ ἄγγελοι διηκόνουν αὐτῷ.", "And he was in the wilderness forty days, being tempted by Satan; and he was with the wild animals, and the angels were serving him."],
  ["Rom 3:19", "οἴδαμεν δὲ ὅτι ὅσα ὁ νόμος λέγει τοῖς ἐν τῷ νόμῳ λαλεῖ, ἵνα πᾶν στόμα φραγῇ καὶ ὑπόδικος γένηται πᾶς ὁ κόσμος τῷ θεῷ·", "Now we know that whatever the law says, it speaks to those under the law, so that every mouth may be stopped and the whole world may be held accountable to God."],
  ["Rom 3:20", "διότι ἐξ ἔργων νόμου οὐ δικαιωθήσεται πᾶσα σὰρξ ἐνώπιον αὐτοῦ, διὰ γὰρ νόμου ἐπίγνωσις ἁμαρτίας.", "For by works of the law no flesh will be justified before him, for through the law comes knowledge of sin."],
  ["Rom 3:21", "Νυνὶ δὲ χωρὶς νόμου δικαιοσύνη θεοῦ πεφανέρωται μαρτυρουμένη ὑπὸ τοῦ νόμου καὶ τῶν προφητῶν,", "But now apart from the law the righteousness of God has been revealed, being witnessed by the Law and the Prophets,"],
  ["Rom 3:22", "δικαιοσύνη δὲ θεοῦ διὰ πίστεως Ἰησοῦ Χριστοῦ εἰς πάντας τοὺς πιστεύοντας. οὐ γάρ ἐστιν διαστολή,", "the righteousness of God through faith in Jesus Christ for all who believe. For there is no distinction,"],
  ["Rom 3:23", "πάντες γὰρ ἥμαρτον καὶ ὑστεροῦνται τῆς δόξης τοῦ θεοῦ", "for all have sinned and fall short of the glory of God,"],
  ["Rom 3:24", "δικαιούμενοι δωρεὰν τῇ αὐτοῦ χάριτι διὰ τῆς ἀπολυτρώσεως τῆς ἐν Χριστῷ Ἰησοῦ·", "being justified freely by his grace through the redemption that is in Christ Jesus,"],
  ["Rom 3:25", "ὃν προέθετο ὁ θεὸς ἱλαστήριον διὰ πίστεως ἐν τῷ αὐτοῦ αἵματι εἰς ἔνδειξιν τῆς δικαιοσύνης αὐτοῦ διὰ τὴν πάρεσιν τῶν προγεγονότων ἁμαρτημάτων", "whom God put forward as a propitiation, through faith, by his blood, to show his righteousness, because he had passed over the sins previously committed"],
  ["Rom 3:26", "ἐν τῇ ἀνοχῇ τοῦ θεοῦ, πρὸς τὴν ἔνδειξιν τῆς δικαιοσύνης αὐτοῦ ἐν τῷ νῦν καιρῷ, εἰς τὸ εἶναι αὐτὸν δίκαιον καὶ δικαιοῦντα τὸν ἐκ πίστεως Ἰησοῦ.", "in the forbearance of God — to show his righteousness at the present time, so that he might be just and the justifier of the one who has faith in Jesus."],
].map(([ref, g, a]) => ({ src: "Translate", sec: ref, p: "Translate.", g, a }));

window.CARDS = [...QUIZ, ...CH12, ...PASSAGE, ...TRANSLATE].map((c) => ({ ...c, id: `${c.src}|${c.sec}|${c.n ?? ""}|${c.g || c.p}` }));
